<wsdl:definitions name="MFOrder" targetNamespace="http://bsestarmf.in/">
    <wsp:Policy wsu:Id="WSHttpBinding_MFOrderEntry_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsaw:UsingAddressing/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="WSHttpBinding_MFOrderEntry1_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                    </wsp:Policy>
                </sp:TransportBinding>
                <wsaw:UsingAddressing/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://bsestarmf.in/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/MFOrderService"/>
            <xs:element name="getPassword">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getPasswordResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="getPasswordResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="OrderEntry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="data" nillable="true" type="q1:OrderData"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="OrderEntryResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="OrderEntryResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="orderEntryParam">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="TransCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="TransNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SchemeCd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Qty" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="AllRedeem" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="RefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SubBrCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Parma1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MobileNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EmailID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MandateID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="orderEntryParamResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="orderEntryParamResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="spreadOrderEntry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="data" nillable="true" type="q2:SpreadOrder"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="spreadOrderEntryResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="spreadOrderEntryResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="spreadOrderEntryParam">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="TransactionCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UniqueRefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SchemeCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderValue" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="RedemptionAmt" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="AllUnitFlag" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="RedeemDate" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="RefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SubBroCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="IPAddress" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MobileNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EmailID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="spreadOrderEntryParamResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="spreadOrderEntryParamResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="switchOrderEntry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="data" nillable="true" type="q3:SwitchOrder"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="switchOrderEntryResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="switchOrderEntryResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="switchOrderEntryParam">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="TransCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="TransNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FromSchemeCd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ToSchemeCd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="OrderVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SwitchUnits" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="AllUnitsFlag" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SubBrCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Parma1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="switchOrderEntryParamResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="switchOrderEntryParamResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sipOrderEntry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="data" nillable="true" type="q4:SipOrder"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sipOrderEntryResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="sipOrderEntryResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sipOrderEntryParam">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="TransactionCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UniqueRefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SchemeCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MemberCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="InternalRefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="TransMode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DpTxnMode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="StartDate" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FrequencyType" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FrequencyAllowed" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="InstallmentAmount" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="NoOfInstallment" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FirstOrderFlag" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SubberCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Euin" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EuinVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="RegId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sipOrderEntryParamResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="sipOrderEntryParamResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="xsipOrderEntry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="data" nillable="true" type="q5:XsipOrder"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="xsipOrderEntryResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="xsipOrderEntryResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="xsipOrderEntryParam">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="TransactionCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UniqueRefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SchemeCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MemberCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="InternalRefNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="TransMode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DpTxnMode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="StartDate" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FrequencyType" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FrequencyAllowed" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="InstallmentAmount" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="NoOfInstallment" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="FirstOrderFlag" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Brokerage" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="MandateID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="SubberCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Euin" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="EuinVal" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="XsipRegID" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="xsipOrderEntryParamResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="xsipOrderEntryParamResult" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/MFOrderService">
            <xs:complexType name="OrderData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AllRedeem" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EmailID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MandateID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MobileNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Qty" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="RefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SchemeCd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SubBrCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="OrderData" nillable="true" type="tns:OrderData"/>
            <xs:complexType name="SpreadOrder">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AllUnitFlag" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EmailID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MobileNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="RedeemDate" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="RedemptionAmt" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="RefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SchemeCd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SubBrCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="SpreadOrder" nillable="true" type="tns:SpreadOrder"/>
            <xs:complexType name="SwitchOrder">
                <xs:sequence>
                    <xs:element minOccurs="0" name="AllUnitFlag" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySell" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="BuySellType" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPTxn" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUIN" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EUINVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FromSchemeCd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="KYCStatus" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MemberId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MinRedeem" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="OrderVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SubBrCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SwitchUnits" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ToSchemeCd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="SwitchOrder" nillable="true" type="tns:SwitchOrder"/>
            <xs:complexType name="SipOrder">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPTxnMode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Euin" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EuinVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FirstOrderFlag" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FrequencyAllowed" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FrequencyType" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="InstallmentAmount" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="InternalRefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MemberCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="NoOfInstallments" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="RegId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SchemeCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="StartDate" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SubberCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransMode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransactionCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UniqueRefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UserID" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="SipOrder" nillable="true" type="tns:SipOrder"/>
            <xs:complexType name="XsipOrder">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Brokerage" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ClientCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DPC" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="DpTxnMode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Euin" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="EuinVal" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler4" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler5" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Filler6" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FirstOrderFlag" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FolioNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FrequencyAllowed" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="FrequencyType" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="IPAdd" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="InstallmentAmount" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="InternalRefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MandateID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="MemberCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="NoOfInstallment" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param1" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param2" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Param3" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PassKey" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Password" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Remarks" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SchemeCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="StartDate" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="SubberCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransMode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TransactionCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UniqueRefNo" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="XsipRegID" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="XsipOrder" nillable="true" type="tns:XsipOrder"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="MFOrderEntry_getPassword_InputMessage">
        <wsdl:part name="parameters" element="tns:getPassword"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_getPassword_OutputMessage">
        <wsdl:part name="parameters" element="tns:getPasswordResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_OrderEntry_InputMessage">
        <wsdl:part name="parameters" element="tns:OrderEntry"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_OrderEntry_OutputMessage">
        <wsdl:part name="parameters" element="tns:OrderEntryResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_orderEntryParam_InputMessage">
        <wsdl:part name="parameters" element="tns:orderEntryParam"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_orderEntryParam_OutputMessage">
        <wsdl:part name="parameters" element="tns:orderEntryParamResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_spreadOrderEntry_InputMessage">
        <wsdl:part name="parameters" element="tns:spreadOrderEntry"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_spreadOrderEntry_OutputMessage">
        <wsdl:part name="parameters" element="tns:spreadOrderEntryResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_spreadOrderEntryParam_InputMessage">
        <wsdl:part name="parameters" element="tns:spreadOrderEntryParam"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_spreadOrderEntryParam_OutputMessage">
        <wsdl:part name="parameters" element="tns:spreadOrderEntryParamResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_switchOrderEntry_InputMessage">
        <wsdl:part name="parameters" element="tns:switchOrderEntry"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_switchOrderEntry_OutputMessage">
        <wsdl:part name="parameters" element="tns:switchOrderEntryResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_switchOrderEntryParam_InputMessage">
        <wsdl:part name="parameters" element="tns:switchOrderEntryParam"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_switchOrderEntryParam_OutputMessage">
        <wsdl:part name="parameters" element="tns:switchOrderEntryParamResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_sipOrderEntry_InputMessage">
        <wsdl:part name="parameters" element="tns:sipOrderEntry"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_sipOrderEntry_OutputMessage">
        <wsdl:part name="parameters" element="tns:sipOrderEntryResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_sipOrderEntryParam_InputMessage">
        <wsdl:part name="parameters" element="tns:sipOrderEntryParam"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_sipOrderEntryParam_OutputMessage">
        <wsdl:part name="parameters" element="tns:sipOrderEntryParamResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_xsipOrderEntry_InputMessage">
        <wsdl:part name="parameters" element="tns:xsipOrderEntry"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_xsipOrderEntry_OutputMessage">
        <wsdl:part name="parameters" element="tns:xsipOrderEntryResponse"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_xsipOrderEntryParam_InputMessage">
        <wsdl:part name="parameters" element="tns:xsipOrderEntryParam"/>
    </wsdl:message>
    <wsdl:message name="MFOrderEntry_xsipOrderEntryParam_OutputMessage">
        <wsdl:part name="parameters" element="tns:xsipOrderEntryParamResponse"/>
    </wsdl:message>
    <wsdl:portType name="MFOrderEntry">
        <wsdl:operation name="getPassword">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/getPassword" message="tns:MFOrderEntry_getPassword_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/getPasswordResponse" message="tns:MFOrderEntry_getPassword_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="OrderEntry">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/OrderEntry" message="tns:MFOrderEntry_OrderEntry_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/OrderEntryResponse" message="tns:MFOrderEntry_OrderEntry_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="orderEntryParam">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/orderEntryParam" message="tns:MFOrderEntry_orderEntryParam_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/orderEntryParamResponse" message="tns:MFOrderEntry_orderEntryParam_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntry">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntry" message="tns:MFOrderEntry_spreadOrderEntry_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryResponse" message="tns:MFOrderEntry_spreadOrderEntry_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntryParam">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam" message="tns:MFOrderEntry_spreadOrderEntryParam_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParamResponse" message="tns:MFOrderEntry_spreadOrderEntryParam_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntry">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntry" message="tns:MFOrderEntry_switchOrderEntry_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntryResponse" message="tns:MFOrderEntry_switchOrderEntry_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntryParam">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam" message="tns:MFOrderEntry_switchOrderEntryParam_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParamResponse" message="tns:MFOrderEntry_switchOrderEntryParam_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntry">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntry" message="tns:MFOrderEntry_sipOrderEntry_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntryResponse" message="tns:MFOrderEntry_sipOrderEntry_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntryParam">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam" message="tns:MFOrderEntry_sipOrderEntryParam_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParamResponse" message="tns:MFOrderEntry_sipOrderEntryParam_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntry">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntry" message="tns:MFOrderEntry_xsipOrderEntry_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryResponse" message="tns:MFOrderEntry_xsipOrderEntry_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntryParam">
            <wsdl:input wsaw:Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam" message="tns:MFOrderEntry_xsipOrderEntryParam_InputMessage"/>
            <wsdl:output wsaw:Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParamResponse" message="tns:MFOrderEntry_xsipOrderEntryParam_OutputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="WSHttpBinding_MFOrderEntry" type="tns:MFOrderEntry">
        <wsp:PolicyReference URI="#WSHttpBinding_MFOrderEntry_policy"/>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getPassword">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/getPassword" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="OrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/OrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="orderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/orderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="WSHttpBinding_MFOrderEntry1" type="tns:MFOrderEntry">
        <wsp:PolicyReference URI="#WSHttpBinding_MFOrderEntry1_policy"/>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getPassword">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/getPassword" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="OrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/OrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="orderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/orderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="spreadOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="switchOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="sipOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntry">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntry" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="xsipOrderEntryParam">
            <soap12:operation soapAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MFOrder">
        <wsdl:port name="WSHttpBinding_MFOrderEntry" binding="tns:WSHttpBinding_MFOrderEntry">
            <soap12:address location="http://pbustarmfsrv113.bseltd.domain/MFOrderEntry/MFOrder.svc"/>
            <wsa10:EndpointReference>
                <wsa10:Address>
                    http://pbustarmfsrv113.bseltd.domain/MFOrderEntry/MFOrder.svc
                </wsa10:Address>
            </wsa10:EndpointReference>
        </wsdl:port>
        <wsdl:port name="WSHttpBinding_MFOrderEntry1" binding="tns:WSHttpBinding_MFOrderEntry1">
            <soap12:address location="https://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc/Secure"/>
            <wsa10:EndpointReference>
                <wsa10:Address>
                    https://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc/Secure
                </wsa10:Address>
            </wsa10:EndpointReference>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>